name: CI Lab Workflow

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Break the build
        run: exit 1
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Robot is working successfully!"
